### ISSUE TITLE
[Mod Support] Farmer's Delight integration

### ISSUE THREAD

**Issue by MrGreenTea** [hybridlabs/hybrid-aquatic#1]
I would love if the meats and other food items from this mod where somehow integrated with Farmer's Delight.

Perhaps the raw fish meats could get the tag `#c:raw_fishes` added?
There is also the `#farmersdelight:cabbage_roll_ingredient` tag and maybe even more?

Also could add some rolls similar to the existing Salmon Roll and Cod Roll?

**Comment by dragonflame86** [comment]
Will definitely look into it for the upcoming updates.

**Comment by dragonflame86** [comment]
Accidentally closed, will come back and update this thread at a later date.

**Comment by steve-the-player** [comment]
It might be easier to make a separate delight compat mod. That's how a lot of mods go about it (for example, End's Delight adds to BetterEnd, and Nether's Delight adds to the base Nether). Aquatic Delight has a nice ring to it.

**Comment by MysticKoko** [comment]
Being worked on as we speak, should be included soon.

**Comment by MysticKoko** [comment]
Done - should be present in the next patch or so
