### ISSUE TITLE
Crash caused by texture

### ISSUE THREAD

**Issue by Lolothepro** [hybridlabs/hybrid-aquatic#11]
```
Failed to load texture: hybrid-aquatic:textures/entity/block/plushie/crab_plushie.png
java.io.FileNotFoundException: hybrid-aquatic:textures/entity/block/plushie/crab_plushie.png
```

**Comment by MysticKoko** [comment]
Hey, sorry for the late reply, was busy with university.
Just looked at this, and I think I managed to fix it. It should be fixed in the next update

Edit: confirmed that its fixed, will mark it as resolved
