### ISSUE TITLE
Basking Shark's attack crashes Fabric server

### ISSUE THREAD

**Issue by ZiLenTz** [hybridlabs/hybrid-aquatic#12]
Tried to attack Basking Shark which went fine.
However, after it's about to retaliate, the server crashed.
Also it wasn't just once, I was basically stuck there for few minutes as the server kept crashing while I was trying to get away from it.

Crash log: https://mclo.gs/R7hJpyq

Note: config option to disable certain entity spawns would be nice addition regardless of the issue. : )

Minecraft 1.20.1
Fabric Loader 0.15.6
Hybrid Aquatic 1.2.2

**Comment by Ivan-Khar** [comment]
Will be fixed in the next update
