### ISSUE TITLE
[Compat] Crash with Golden Foods! mod

### ISSUE THREAD

**Issue by VaporeonScripts** [hybridlabs/hybrid-aquatic#15]
when i add ur mod to my server, the server wont boot cause of errors, here the log:
![image](https://github.com/hybridlabs/hybrid-aquatic/assets/133986238/c48c0081-444b-44bd-9b35-fb6a96a9d7ff)

**Comment by Ivan-Khar** [comment]
You need to post the whole log file + list of all mods + their versions that you've got

**Comment by VaporeonScripts** [comment]
all mods are 1.20.4 and they are 300, also yeah, wait a sec ima send the whole log

**Comment by VaporeonScripts** [comment]
how can i send the full log?

**Comment by Ivan-Khar** [comment]
Use https://pastebin.com/ or https://mclo.gs/. Or just attach the log file

**Comment by VaporeonScripts** [comment]
i cant find the log file of server, i will need re add the mod and send the log ig

**Comment by VaporeonScripts** [comment]
even with the latest version, server wont boot: 
[latest.log](https://github.com/hybridlabs/hybrid-aquatic/files/15024279/latest.log)

**Comment by Ivan-Khar** [comment]
mod incompatibility with https://www.curseforge.com/minecraft/mc-mods/golden-foods
gonna be fixed in the next update 07af6aa47bee1bbe4ee6b82b0497c6bcf6a8fb99

**Comment by Ivan-Khar** [comment]
Actually nevermind, it's not fixed but yeah it is compat issue with golden foods mod

**Comment by VaporeonScripts** [comment]
how could that be? golden food always worked

**Comment by Ivan-Khar** [comment]
Issue is on "Golden Foods!" side. They need to learn how to modify loot tables instead of @ Redirect'ing. Clashes with our mixin that changes items to real fish entities when you have "Live Catch" enchantment. Also probably gonna be fixed at some point in the future on our side
https://docs.minecraftforge.net/en/1.20.x/resources/server/glm/>
https://fabricmc.net/wiki/tutorial:adding_to_loot_tables>

**Comment by VaporeonScripts** [comment]
oh ok ,so if i remove golden food mod it wont crash?

**Comment by Ivan-Khar** [comment]
Yes

**Comment by VaporeonScripts** [comment]
oooh cool, i always loved fish mods, im so happy that finally i can play this mod with more than 30 different fishes xD, btw a cool idea for a fish could be lantern fish xd

**Comment by VaporeonScripts** [comment]
removing golden food mod and adding midas hunger mod (another gold food mod) makes server work with hybrid aquatic mod! hope golden food mod finds a way to be compatible with ur mod
