### ISSUE TITLE
crabs and lobsters and similar animals almost instantly die on land which isn't realistic

### ISSUE THREAD

**Issue by Dashy22** [hybridlabs/hybrid-aquatic#17]
In the mod i see dead crawfish on land everywhere and crabs too. But in real life crabs live outside and inside water while in the mod they don't even last 10 seconds out of water.

Your crabs and lobsters are cool but I never see them on beaches or around rivers, well just their carcasses.

**Comment by MysticKoko** [comment]
They are meant to navigate towards water when they are starting to dehydrate - its a bug that theyre not doing so

Will look into it and fix it in the next patch

**Comment by Dashy22** [comment]
good but crabs and stuff don't dehydrate and die that fast. I see crayfish step out the water and practically instantly die.

**Comment by Ivan-Khar** [comment]
should be fixed in the next update
0bc8b4eaa8e21234bf5211948092e0e72790e746
