### ISSUE TITLE
Add a method to move bigger animals like sharks.

### ISSUE THREAD

**Issue by NolanHewitt** [hybridlabs/hybrid-aquatic#19]
It would be nice if there was some way to get them to follow you, so if you wanted to make an aquarium somewhere you could bring them there. Perhaps they could follow you while holding certain kinds if fish like other mobs do with food items they like? Being able to breed some of the bigger animals would be really nice too.

**Comment by MysticKoko** [comment]
For sharks you can move them by getting them to chase you - easily done by punching them once. You can also move them by using a splash potion of bleeding on yourself or a cow/pig/etc and they're all going to relentlessly chase the bleeding entity.

A larger fishing net that'll let you move bigger animals is planned for later on, but for now the above methods will have to do.

**Comment by MysticKoko** [comment]
As of 1.3.3 fishing nets can now move sunfish and oarfish as well, a method to transport sharks will be added at a later date but I will consider this issue closed for the meantime
