### ISSUE TITLE
Crabs die on beaches

### ISSUE THREAD

**Issue by mxKeaton** [hybridlabs/hybrid-aquatic#20]
I think crabs suffocate out of water. They all start to get ticking damage and just die.
I do play with a large mod list and I have heavily modified the modfiles to make the animals spawn on Regions Unexplored biomes. Maybe that is part of the issue.

Running the newest version with the reworked crabs.

![image](https://github.com/hybridlabs/hybrid-aquatic/assets/83590708/a8ba5c72-68e7-4539-8a1d-18508d2ee8ad)

![image](https://github.com/hybridlabs/hybrid-aquatic/assets/83590708/4963439b-a5a1-4fd1-b541-8e0dada83b06)

**Comment by MysticKoko** [comment]
You're still having this issue on 1.3.2?

**Comment by mxKeaton** [comment]
Just realized that I was running 1.3.0 and not the newest version. You updated so fast, I could not catch up.

Thank you and sorry for my outdated report!
