### ISSUE TITLE
(Suggestion) Diving helmet too OP

### ISSUE THREAD

**Issue by Verdigris7** [hybridlabs/hybrid-aquatic#23]
Unsolicited advice just for you guys! ｡◕‿◕｡
The diving helmet can be crafted with 8 copper ingots and a block of glass, yet it has more armor points than a Netherite helmet. 
The infinite water breathing is also pretty OP for such a cheap item, but not as bad as a copper helmet being better than Netherite. 
Maybe it could have downsides like giving you slowness when on land, a diving helmet overlay that obscures vision, or having less than infinite water breathing?
At the very least I think such a useful item should not also have higher armor points than every vanilla helmet.

**Comment by MysticKoko** [comment]
Checked our code and this was just a bug left in from when we were playing around with armor values, will be fixed in the next update.
Thank you for your report <3

**Comment by DarianLStephens** [comment]
I very much agree that it's too powerful.
Not even the armor value, it just lets you breathe underwater forever! You only need the helmet, too, so you only have to sacrifice one piece of armor to never have to worry about water breathing potions, respiration, air pockets, just coming to the surface, or anything.
If they're not willing to make the water breathing limited, then I do like the idea of giving it a Pumpkin-like overlay to naturally encourage you to take it off every now and then.
Even if it can be worked around with resource packs, that's cheating.

Heck, I'd like to see the item able to be disabled with the config, in favor of maybe Create's diving suit or other alternatives which aren't quite so ridiculously powerful.

**Comment by MysticKoko** [comment]
An overlay was already being worked on for the next update, although it's still very much in the experimental phase to make sure it doesn't completely ruin visibility.
Will look into reducing the water breathing effect as well

**Comment by ginsm** [comment]
Maybe make it more like respiration rather than water breathing?

**Comment by MysticKoko** [comment]
> Maybe make it more like respiration rather than water breathing?

We made it so the the water breathing effect will not be replenished underwater, so you will eventually have to swim up for air and to reset the effect timer, similar to how turtle helmets work

**Comment by MysticKoko** [comment]
Diving armor has been nerfed with the 1.3.3 update. All its armor values have been rebalanced and the diving helmet now applies an overlay when worn. The diving helmet also now only applies water breathing for 30 seconds, and only when worn outside of water first. You can't put the helmet on underwater and get its water breathing buff (you will still get Clarity though)

Diving boots now make you sink faster in water and prevent you from jumping (pressing space) underwater, instead allowing you to walk up blocks. You can still swim by entering the swimming pose as well.
