### ISSUE TITLE
[1.20.1] Jellyfish (mainly barrel) keep spawning just below floating islands

### ISSUE THREAD

**Issue by MrElectrum** [hybridlabs/hybrid-aquatic#25]
So I've been building a modpack for a personal server, and I have terralith on there, which adds some floating islands that spawn over oceans. When I go near them Barrel Jellyfish spawn in the air just below them and then drop into the ocean. I've tried running mob filtering mods to no avail. It only seems to be the barrel jellyfish, but I would have to test further.

![image](https://github.com/hybridlabs/hybrid-aquatic/assets/172245912/f274d948-1a53-4c7b-9efa-9a71845dd158)

**Comment by MysticKoko** [comment]
Fixed in our dev version and will be released with the next update
