### ISSUE TITLE
Client console keeps spamming "Unable to find animation: idle for SeaAngelEntity"

### ISSUE THREAD

**Issue by samve000** [hybridlabs/hybrid-aquatic#27]
![image](https://github.com/user-attachments/assets/25f9a8d6-c95e-48cc-8c23-c70ec511aed4)

**Comment by MysticKoko** [comment]
I'm aware of this and will fix it with the coming patch (1.3.4), but in the meantime the error is not fatal and wont affect your gameplay in any way

**Comment by MysticKoko** [comment]
Fixed with the 1.3.4 update
