### ISSUE TITLE
Mobs spawning out of water

### ISSUE THREAD

**Issue by LimonFotters** [hybridlabs/hybrid-aquatic#28]
I've had many instances of jellyfish spawning hundreds of blocks high over the ocean around builds and terrain, and also sharks spawning in air blocks on dry land. Anything that can be done to fix that?

**Comment by MysticKoko** [comment]
Which version of the mod are you using? You should be using version 1.3.3 as it contained a lot of bug fixes

**Comment by LimonFotters** [comment]
I’ll see what version I’m using and get back to this
