### ISSUE TITLE
Change Fishing loot tables

### ISSUE THREAD

**Issue by NotSkynet** [hybridlabs/hybrid-aquatic#31]
I uninstalled this mod from the better mc mod pack because it weighs the fish in this mod way too high in the loot tables. For example I went through 9 fishing rods and I only got regular fish and the fish from this mod. It seems to have cut the chances of getting rare loot way way way down to basically non existent levels. If this is as intended please add a way to configure it so that these fish do not show up in loot tables or add a way to change the weights of it like most mods allow.

**Comment by MysticKoko** [comment]
Should be slightly improved in the latest 1.3.4 update
