### ISSUE TITLE
fabric 1.20.1 crash when loading up world

### ISSUE THREAD

**Issue by ibbyzmc** [hybridlabs/hybrid-aquatic#32]
world suddenly crashed and this error appeared. i tried to join my world but at soon as it loads, a sec later and it crashes with this same crash

i think its because it cant find an entity or something? a fix would be nice

modloader: fabric 0.15.11
[crash-2024-07-29_18.57.27-client.txt](https://github.com/user-attachments/files/16417197/crash-2024-07-29_18.57.27-client.txt)

**Comment by MysticKoko** [comment]
Use the latest file uploaded on [Curseforge](https://www.curseforge.com/minecraft/mc-mods/hybrid-aquatic/files/5577243) and [Modrinth](https://modrinth.com/mod/hybrid-aquatic/version/ybVR3g7U), which is a hotfix for this exact crash.
Thank you for your report
