### ISSUE TITLE
Crash on world load with 1.3.4 Hotfix version

### ISSUE THREAD

**Issue by NolanHewitt** [hybridlabs/hybrid-aquatic#33]
[crash-2024-07-30_00.30.29-client.txt](https://github.com/user-attachments/files/16422477/crash-2024-07-30_00.30.29-client.txt)

**Comment by MysticKoko** [comment]
Fixed and uploading a new patch file right now, apologies for the inconvenience.
I've deleted the old 1.3.4 Hotfix file but will be reuploading a file with the same name, please simply reinstall it and it should work fine. You can find it on [Modrinth](https://modrinth.com/mod/hybrid-aquatic/version/YYDAvrfm) and [Curseforge](https://www.curseforge.com/minecraft/mc-mods/hybrid-aquatic/files/5580502)
