### ISSUE TITLE
Coral Tools seems to be missing language.

### ISSUE THREAD

**Issue by NolanHewitt** [hybridlabs/hybrid-aquatic#35]
Playing on Fabric 1.20.1 with the English language, all the coral tools display their name like item.hybrid-aquatic.coral_blade.

**Comment by MysticKoko** [comment]
Coral tools are unfinished so theyre not meant to be used at the moment, that's why you cant find them in any of the inventory tabs. They're only in the mod via commands at the moment until further notice
