### ISSUE TITLE
Jellyfish hell 

### ISSUE THREAD

**Issue by mollenfonken** [hybridlabs/hybrid-aquatic#37]
**Hybrid Aquatic 1.3.2 / Fabric 1.20.1**

Well, I have a problem that is becoming quite annoying, jellyfish and all kinds of fish appear whether there is water or not, it is full of slime all over the area where I have my house and even inside it, they fall and die over and over again, the area where I am is near the sea, but I have removed a lot of the water leaving it dry but they still appear also inside the caves they appear even in very deep levels, they fall, die, and leave slime everywhere and it is very annoying, I don't know what to do anymore to make them disappear without having to uninstall the mod. :))))) (help please) I'm going crazy.

![2024-08-08_19 51 58](https://github.com/user-attachments/assets/6fe180bb-1455-4996-ad61-8ac5e0c61754)
![2024-08-08_19 53 27](https://github.com/user-attachments/assets/6edfab88-9443-4fad-ba67-41390d50d641)
![2024-08-08_19 58 46](https://github.com/user-attachments/assets/bc2d30a4-c99c-4c9e-91f8-e7e59e2c2f7d)
![2024-08-08_19 59 08](https://github.com/user-attachments/assets/6e57148f-7a69-4a8f-bbbb-896957175c3b)

**Comment by MysticKoko** [comment]
Just update to the latest version of the mod, this bug was fixed a while ago lol

**Comment by ghost** [comment]
It is already labeled as a bug but I came here for the same reason. I am using minecraft 1.20.4 and using the latest build mod for this version. In a lot of caves wherever I go I see jellyfish and slime_balls. They all die in the caves because of no water. but just keeps spawning.

**Comment by MysticKoko** [comment]
the 1.20.4 version of the mod doesnt have this bugfix yet but we are working on it

**Comment by ghost** [comment]
Thanks for your fast reply :).
