### ISSUE TITLE
Placed Giant clams spawn with a pearl

### ISSUE THREAD

**Issue by Tera458** [hybridlabs/hybrid-aquatic#39]
Giant clams that are mined and placed back can immediately be clicked to obtain a pearl or black pearl, making it possible to farm pearls by just breaking, placing back and clicking a single clam indefinitely.

**Comment by MysticKoko** [comment]
Think I know a fix for this, will look into it

**Comment by MysticKoko** [comment]
Fixed in the dev version - will be in the next update
