### ISSUE TITLE
Bucketable Fish

### ISSUE THREAD

**Issue by valchiara** [hybridlabs/hybrid-aquatic#9]
I expected to be able to capture the various fish types of this mod in buckets, is this feature planned to be added?

**Comment by Aetherna** [comment]
I second that! The sole reason for adding the mod was to build a giant aquarium. Please please add it, it will bo soo cool!

**Comment by MysticKoko** [comment]
Hey, sorry for the late reply - was busy with university
You can craft a fishing net using sticks and string, which lets you pick up and move every creature in our mod apart from sharks and sunfish, which will have their own method of transportation in the future
